### ISSUE TITLE
This App is not working

### ISSUE THREAD

**Issue by Akarshshettyy** [Hash-Studios/e-learning-app#2]
This project is not working in my system and I have the version 1.17.5. can you update your project for latest version

**Comment by codenameakshay** [comment]
The app is working perfectly on Flutter v1.17.4, therefore it should work just fine on your system too. If you give the output of `flutter run` then I can look, and tell you why it is not working on your system.

**Comment by Akarshshettyy** [comment]
Yeah, Now it worked I upgraded the project's flutter version from 1.0.1 to 1.17.5
