### ISSUE TITLE
Can you post the screenshots of firebase setup?

### ISSUE THREAD

**Issue by Akarshshettyy** [Hash-Studios/e-learning-app#3]

**Comment by codenameakshay** [comment]
The app uses Firebase auth & Cloud Firestore. For Firebase auth, one needs to just implement Google Sign-in which can be done using [this](https://medium.com/flutter-community/flutter-implementing-google-sign-in-71888bca24ed). And for cloud firestore, you just need to enable it from the Firebase console. Then the app will automatically create users whenever they login on the basis of the following schema. 
```
└── users
    └── documentID (AutoID)
        ├── id - 'User ID'
        ├── email - 'User email'
        ├── name - 'User name'
        ├── createdAt - DateTime.now() or timestamp
        └── premium - 'Boolean'
```
This is the only thing needed to done with Firebase and hence I will be closing this issue. If you have any more doubts feel free to reopen this issue.

**Comment by Akarshshettyy** [comment]
Thanks it cleared my doubt with firebase
